# Generated by Django 6.0.2 on 2026-02-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us11_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daynote',
            options={'ordering': ('-date', '-created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='daynote',
            unique_together=set(),
        ),
    ]
