# Generated by Django 5.2.7 on 2026-02-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
