# Generated by Django 5.2.7 on 2026-02-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cycle_id'),
        ('core', '0002_cycle_end_date'),
    ]

    operations = [
    ]
