# Generated by Django 5.2.7 on 2026-02-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_alter_cycle_id_0002_cycle_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
