# Generated by Django 6.0.2 on 2026-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cycle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
