# Generated by Django 6.0.2 on 2026-02-24 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us16_habit_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('intention', models.CharField(blank=True, max_length=140)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='habit',
            name='intention',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('partial', 'A little'), ('not_today', 'Not today'), ('none', 'No entry')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='habit',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_habits', to='us16_habit_tracking.habittemplate'),
        ),
    ]
