# Generated by Django 6.0.2 on 2026-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us13_checkin_prompt', '0002_alter_dailycheckin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
