# Generated by Django 6.0.2 on 2026-02-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us1_create_login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
